### ISSUE TITLE
Server doesn't work

### ISSUE THREAD

**Issue by KitKod** [rosshettel/placegoat#7]
I am sending a test request to the server (I took it from your site page), but I get a 500 error in response. See the attached screenshots below.

![Screenshot_20210108_084131_br.tiagohm.restler.jpg](https://user-images.githubusercontent.com/24569031/103983207-88a9cc80-518d-11eb-8aae-1b1f82e624a2.jpg)

![Screenshot_20210108_084140_br.tiagohm.restler.jpg](https://user-images.githubusercontent.com/24569031/103983221-8fd0da80-518d-11eb-86d5-874bcde7946b.jpg)

![Screenshot_20210108_084209_br.tiagohm.restler.jpg](https://user-images.githubusercontent.com/24569031/103983239-95c6bb80-518d-11eb-9deb-7bf9d4a253a3.jpg)

**Comment by rosshettel** [comment]
Sorry, this service has been abandoned somewhat, officially shut it down for good now. Please use any other placeholder service!
